[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 999999
via-ir = true
remappings = [
    'optimism/=lib/optimism/packages/contracts-bedrock/',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts',
    '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts',
    '@rari-capital/solmate/=lib/solmate/',
    '@base-contracts/=lib/base-contracts',
    'solady/=lib/solady/src/',
    '@lib-keccak/=lib/lib-keccak/contracts/lib',
    'op-enclave/=lib/op-enclave/',
    '@eth-optimism-bedrock/src/universal/interfaces/=lib/optimism/packages/contracts-bedrock/interfaces/universal',
    '@eth-optimism-bedrock/src/L1/interfaces/=lib/optimism/packages/contracts-bedrock/interfaces/L1',
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
